services:
  postgres:
    container_name: shopify-app-db-postgres
    image: postgres:15-alpine
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - 'postgres:/var/lib/mysql'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
volumes:
  postgres:
    driver: local
